const DATA_PART_3 = [
  ["Soul / Funk","2010s",["Anderson .Paak","Leon Bridges","Janelle Monáe","Childish Gambino","Solange","Thundercat","Michael Kiwanuka","D’Angelo","Bruno Mars","Vulfpeck","Hiatus Kaiyote","Cory Henry"]],
  ["Soul / Funk","2020s",["Silk Sonic","Cleo Sol","Jungle","Leon Bridges","Yussef Dayes","Khruangbin","Durand Jones & The Indications","Anderson .Paak","Thundercat","Hiatus Kaiyote","SAULT","Victoria Monét"]],
  ["Latin","1990s",["Selena","Shakira","Ricky Martin","Gloria Estefan","Maná","Enrique Iglesias","Juanes","Celia Cruz","Luis Miguel","Marc Anthony","Los Fabulosos Cadillacs","Cafe Tacvba","Soda Stereo"]],
  ["Latin","2000s",["Shakira","Daddy Yankee","Juanes","Don Omar","Wisin & Yandel","Calle 13","Aventura","Marc Anthony","Celia Cruz","Maná","Enrique Iglesias","Ivy Queen","Los Tigres del Norte"]],
  ["Latin","2010s",["Bad Bunny","J Balvin","Rosalía","Ozuna","Karol G","Maluma","Romeo Santos","Daddy Yankee","Shakira","Calle 13","Nicky Jam","Anitta"]],
  ["Latin","2020s",["Bad Bunny","Karol G","Peso Pluma","Rauw Alejandro","Feid","Bizarrap","Young Miko","Rosalía","Shakira","Anitta","Myke Towers","Grupo Frontera","Carín León"]],
  ["Country","1960s",["Johnny Cash","Patsy Cline","Loretta Lynn","Merle Haggard","Buck Owens","Tammy Wynette","George Jones","Ray Price","Marty Robbins","Porter Wagoner","Glen Campbell","Charley Pride","Conway Twitty"]],
  ["Country","1970s",["Dolly Parton","Willie Nelson","Waylon Jennings","Johnny Cash","Emmylou Harris","Kenny Rogers","Loretta Lynn","George Jones","Tammy Wynette","Merle Haggard","John Denver","Glen Campbell","Kris Kristofferson"]],
  ["Country","1980s",["Dolly Parton","George Strait","Reba McEntire","Alabama","Randy Travis","The Judds","Hank Williams Jr.","Willie Nelson","Kenny Rogers","George Jones","Dwight Yoakam","Steve Earle","Rosanne Cash"]],
  ["Country","1990s",["Garth Brooks","Shania Twain","George Strait","Alan Jackson","The Chicks","Brooks & Dunn","Tim McGraw","Reba McEntire","Faith Hill","Vince Gill","Dwight Yoakam","Mary Chapin Carpenter","Trisha Yearwood"]],
  ["Country","2000s",["Carrie Underwood","Keith Urban","Brad Paisley","Kenny Chesney","Tim McGraw","Faith Hill","The Chicks","Shania Twain","George Strait","Alan Jackson","Toby Keith","Miranda Lambert","Sugarland"]],
  ["Country","2010s",["Chris Stapleton","Kacey Musgraves","Luke Combs","Eric Church","Miranda Lambert","Maren Morris","Zac Brown Band","Sturgill Simpson","Jason Isbell","Tyler Childers","Brandi Carlile","Little Big Town","Margo Price"]],
  ["Country","2020s",["Morgan Wallen","Zach Bryan","Chris Stapleton","Luke Combs","Lainey Wilson","Jelly Roll","Megan Moroney","Kacey Musgraves","Tyler Childers","Sierra Ferrell","Charley Crockett","Orville Peck","Sturgill Simpson"]],
  ["Metal","1970s",["Black Sabbath","Judas Priest","Motörhead","Deep Purple","Rainbow","Scorpions","Blue Öyster Cult","UFO","Thin Lizzy","Accept"]],
  ["Metal","1980s",["Metallica","Iron Maiden","Slayer","Megadeth","Judas Priest","Ozzy Osbourne","Dio","Anthrax","Mötley Crüe","Def Leppard","Testament","Mercyful Fate"]],
  ["Metal","1990s",["Metallica","Pantera","Tool","Nine Inch Nails","Rage Against the Machine","Korn","Deftones","Alice in Chains","Soundgarden","Sepultura","Faith No More","Marilyn Manson"]],
  ["Metal","2000s",["System of a Down","Slipknot","Tool","Deftones","Avenged Sevenfold","Mastodon","Lamb of God","Disturbed","Killswitch Engage","Linkin Park","Opeth","Queens of the Stone Age"]],
  ["Metal","2010s",["Ghost","Bring Me the Horizon","Avenged Sevenfold","Gojira","Mastodon","Deafheaven","BABYMETAL","Parkway Drive","Architects","Tool","Baroness","Code Orange"]],
  ["Metal","2020s",["Sleep Token","Spiritbox","Knocked Loose","Ghost","Bring Me the Horizon","Gojira","Bad Omens","Lorna Shore","Jinjer","Architects","Turnstile","Loathe"]],
  ["Jazz","1960s",["Miles Davis","John Coltrane","Thelonious Monk","Charles Mingus","Ella Fitzgerald","Nina Simone","Dave Brubeck","Stan Getz","Duke Ellington","Sarah Vaughan","Wes Montgomery","Ornette Coleman"]],
  ["Jazz","1970s",["Miles Davis","Herbie Hancock","Weather Report","Chick Corea","Alice Coltrane","Sun Ra","Return to Forever","George Benson","Keith Jarrett","Pharoah Sanders","McCoy Tyner","Roy Ayers"]],
  ["Jazz","1980s",["Herbie Hancock","Pat Metheny Group","Wynton Marsalis","Miles Davis","Weather Report","Keith Jarrett","Chick Corea","Bobby McFerrin","Branford Marsalis","George Benson","Art Blakey","Ornette Coleman"]],
  ["Jazz","1990s",["Pat Metheny","Wynton Marsalis","Herbie Hancock","Joshua Redman","Cassandra Wilson","Diana Krall","Brad Mehldau","Medeski Martin & Wood","Roy Hargrove","John Scofield","The Bad Plus","Charlie Haden"]],
  ["Jazz","2000s",["Herbie Hancock","Esperanza Spalding","Robert Glasper","Norah Jones","Diana Krall","Brad Mehldau","Hiromi","Snarky Puppy","Avishai Cohen","The Bad Plus","Roy Hargrove","Madeleine Peyroux"]],
  ["Jazz","2010s",["Kamasi Washington","Esperanza Spalding","Robert Glasper","Thundercat","Snarky Puppy","Hiromi","BADBADNOTGOOD","Nubya Garcia","Yussef Kamaal","Sons of Kemet","Christian Scott aTunde Adjuah","Terrace Martin"]],
];
