const DATA_PART_1 = [
  ["Rock","1960s",["The Beatles","The Rolling Stones","Jimi Hendrix","The Who","Led Zeppelin","Janis Joplin","The Doors","The Beach Boys","The Kinks","Cream","Creedence Clearwater Revival","Jefferson Airplane","The Velvet Underground"]],
  ["Rock","1970s",["Led Zeppelin","Fleetwood Mac","Queen","David Bowie","Bruce Springsteen","Aerosmith","The Clash","Heart","Boston","Cheap Trick","Journey","Pink Floyd","Eagles","AC/DC","Lynyrd Skynyrd"]],
  ["Rock","1980s",["U2","Bruce Springsteen","Guns N' Roses","Bon Jovi","The Cure","Dire Straits","Van Halen","The Police","Talking Heads","Journey","R.E.M.","Metallica","INXS"]],
  ["Rock","1990s",["Nirvana","Pearl Jam","Radiohead","Red Hot Chili Peppers","Oasis","Foo Fighters","Green Day","Soundgarden","Alice in Chains","The Smashing Pumpkins","Rage Against the Machine","Nine Inch Nails","Weezer"]],
  ["Rock","2000s",["The White Stripes","The Killers","Arctic Monkeys","Muse","Linkin Park","Kings of Leon","Paramore","Coldplay","The Strokes","Queens of the Stone Age","The Black Keys","Evanescence","System of a Down"]],
  ["Rock","2010s",["Tame Impala","The 1975","Imagine Dragons","Twenty One Pilots","Vampire Weekend","HAIM","Mitski","Arctic Monkeys","Florence + the Machine","The Black Keys","The National","Foals","Queens of the Stone Age"]],
  ["Rock","2020s",["Måneskin","Wet Leg","boygenius","Fontaines D.C.","Turnstile","The Last Dinner Party","Sam Fender","IDLES","Paramore","The Smile","King Gizzard & the Lizard Wizard","Nothing But Thieves","The War on Drugs"]],
  ["Pop","1980s",["Michael Jackson","Madonna","Prince","Whitney Houston","George Michael","Cyndi Lauper","Janet Jackson","Phil Collins","Paula Abdul","Belinda Carlisle","a-ha","Tina Turner","Cher","Kate Bush","Hall & Oates","Kylie Minogue"]],
  ["Pop","1990s",["Mariah Carey","Britney Spears","Backstreet Boys","Spice Girls","Janet Jackson","Celine Dion","Christina Aguilera","George Michael","NSYNC","TLC","No Doubt","Shania Twain","Ace of Base"]],
  ["Pop","2000s",["Beyoncé","Lady Gaga","Rihanna","Justin Timberlake","Pink","Kelly Clarkson","Shakira","Britney Spears","Christina Aguilera","Gwen Stefani","Nelly Furtado","Avril Lavigne","Miley Cyrus"]],
  ["Pop","2010s",["Taylor Swift","Adele","Bruno Mars","Ariana Grande","The Weeknd","Katy Perry","Dua Lipa","Ed Sheeran","Justin Bieber","Miley Cyrus","Lorde","Selena Gomez","Sia"]],
  ["Pop","2020s",["Billie Eilish","Olivia Rodrigo","Sabrina Carpenter","Chappell Roan","Dua Lipa","Doja Cat","Harry Styles","Benson Boone","Tate McRae","Gracie Abrams","Teddy Swims","Miley Cyrus","The Weeknd","Charli xcx","Troye Sivan","Post Malone","RAYE"]],
  ["Hip-Hop","1980s",["Run-D.M.C.","LL Cool J","Public Enemy","Beastie Boys","N.W.A","Eric B. & Rakim","Salt-N-Pepa","A Tribe Called Quest","De La Soul","Ice-T","KRS-One","Slick Rick","Queen Latifah"]],
  ["Hip-Hop","1990s",["2Pac","The Notorious B.I.G.","Nas","Jay-Z","Wu-Tang Clan","OutKast","Snoop Dogg","A Tribe Called Quest","Dr. Dre","Lauryn Hill","Ice Cube","Missy Elliott","DMX","Busta Rhymes"]],
  ["Hip-Hop","2000s",["Kanye West","Eminem","50 Cent","Lil Wayne","OutKast","Missy Elliott","T.I.","Jay-Z","Nas","Snoop Dogg","Ludacris","Clipse","The Roots","Kid Cudi"]],
  ["Hip-Hop","2010s",["Kendrick Lamar","Drake","J. Cole","Travis Scott","Nicki Minaj","Future","Tyler, the Creator","A$AP Rocky","21 Savage","Migos","Mac Miller","Childish Gambino","Pusha T","Schoolboy Q","Vince Staples","Run the Jewels","Cardi B"]],
  ["Hip-Hop","2020s",["Kendrick Lamar","Tyler, the Creator","Doechii","Playboi Carti","Megan Thee Stallion","JID","Little Simz","Travis Scott","Future","21 Savage","Ice Spice","Central Cee","Denzel Curry","Baby Keem"]],
  ["R&B","1970s",["Stevie Wonder","Marvin Gaye","Diana Ross","Earth, Wind & Fire","Al Green","Chaka Khan","The Isley Brothers","Curtis Mayfield","Gladys Knight","Patti LaBelle","Roberta Flack","Bill Withers","Donny Hathaway"]],
  ["R&B","1980s",["Prince","Whitney Houston","Janet Jackson","Sade","Anita Baker","Luther Vandross","Lionel Richie","Michael Jackson","George Michael","Teddy Pendergrass","The Gap Band","New Edition","Patti LaBelle"]],
  ["R&B","1990s",["Mariah Carey","TLC","Mary J. Blige","Usher","Aaliyah","Boyz II Men","Lauryn Hill","D’Angelo","Erykah Badu","Brandy","Monica","Maxwell","SWV"]],
  ["R&B","2000s",["Beyoncé","Usher","Alicia Keys","Amy Winehouse","Ne-Yo","Mary J. Blige","Erykah Badu","D’Angelo","Jill Scott","John Legend","Destiny’s Child","Ciara","Keyshia Cole"]],
  ["R&B","2010s",["Frank Ocean","The Weeknd","SZA","Solange","Miguel","Jhené Aiko","Daniel Caesar","Beyoncé","Alicia Keys","The Internet","H.E.R.","Jorja Smith","Sampha"]],
  ["R&B","2020s",["SZA","Summer Walker","Steve Lacy","Victoria Monét","Cleo Sol","Giveon","Tems","Beyoncé","Frank Ocean","Jorja Smith","Sampha","Brent Faiyaz","Coco Jones"]],
  ["Electronic","1980s",["New Order","Depeche Mode","Pet Shop Boys","Kraftwerk","The Human League","Tears for Fears","Yazoo","Gary Numan","Art of Noise","Yellow Magic Orchestra","Tangerine Dream","Jean-Michel Jarre"]],
  ["Electronic","1990s",["Daft Punk","The Chemical Brothers","The Prodigy","Fatboy Slim","Underworld","Moby","Orbital","Aphex Twin","Björk","Massive Attack","Portishead","Boards of Canada","Leftfield"]],
];
