const DATA_PART_2 = [
  ["Electronic","2000s",["Daft Punk","Justice","LCD Soundsystem","Deadmau5","The Chemical Brothers","M83","Calvin Harris","Aphex Twin","Björk","The Knife","Hot Chip","Soulwax","Moderat"]],
  ["Electronic","2010s",["Calvin Harris","Disclosure","Flume","Skrillex","ODESZA","Zedd","Major Lazer","Jamie xx","Four Tet","Caribou","Flying Lotus","Nicolas Jaar","SOPHIE"]],
  ["Electronic","2020s",["Fred again..","Jamie xx","Peggy Gou","Four Tet","Barry Can't Swim","RÜFÜS DU SOL","Bicep","Charli xcx","Skrillex","Overmono","Floating Points","Romy","Justice"]],
  ["Indie / Alternative","1980s",["The Smiths","The Cure","R.E.M.","Sonic Youth","Pixies","New Order","Cocteau Twins","Talking Heads","The Jesus and Mary Chain","My Bloody Valentine","The Stone Roses","Bauhaus","Joy Division"]],
  ["Indie / Alternative","1990s",["Radiohead","Oasis","Blur","Beck","The Smashing Pumpkins","Pulp","Mazzy Star","Björk","Pavement","PJ Harvey","Portishead","Sonic Youth","Nick Cave & the Bad Seeds"]],
  ["Indie / Alternative","2000s",["Arcade Fire","The Strokes","Yeah Yeah Yeahs","Vampire Weekend","Interpol","MGMT","Phoenix","The National","Bon Iver","TV on the Radio","The Shins","Sufjan Stevens"]],
  ["Indie / Alternative","2010s",["Tame Impala","Lana Del Rey","The xx","Vampire Weekend","Florence + the Machine","Bon Iver","Lorde","Mitski","St. Vincent","The National","Mac DeMarco","Beach House","Father John Misty"]],
  ["Indie / Alternative","2020s",["boygenius","Phoebe Bridgers","Japanese Breakfast","Big Thief","Wet Leg","Mk.gee","Clairo","Fontaines D.C.","The Smile","Wednesday","MJ Lenderman","Black Country, New Road","Alex G"]],
  ["Dance / Disco","1970s",["Donna Summer","Bee Gees","Chic","Diana Ross","ABBA","Earth, Wind & Fire","Gloria Gaynor","KC and the Sunshine Band","Sister Sledge","Village People","The Jacksons","Grace Jones"]],
  ["Dance / Disco","1980s",["Madonna","Prince","Janet Jackson","Pet Shop Boys","New Order","Kylie Minogue","Grace Jones","Donna Summer","Whitney Houston","Cyndi Lauper","Eurythmics","The Pointer Sisters"]],
  ["Dance / Disco","1990s",["Madonna","Jamiroquai","Daft Punk","Robin S.","Crystal Waters","Basement Jaxx","Faithless","Kylie Minogue","The Prodigy","CeCe Peniston","Ultra Naté","Deee-Lite"]],
  ["Dance / Disco","2000s",["Daft Punk","Kylie Minogue","Justice","LCD Soundsystem","Basement Jaxx","Róisín Murphy","Scissor Sisters","Madonna","Robyn","The Rapture","Goldfrapp","Sophie Ellis-Bextor"]],
  ["Dance / Disco","2010s",["Calvin Harris","Dua Lipa","Disclosure","Robyn","Jessie Ware","Chromeo","Major Lazer","Lady Gaga","Kylie Minogue","Róisín Murphy","Sophie Ellis-Bextor","Years & Years"]],
  ["Dance / Disco","2020s",["Dua Lipa","Jessie Ware","Charli xcx","Peggy Gou","Romy","Kaytranada","Jungle","Beyoncé","RAYE","SG Lewis","Purple Disco Machine","Confidence Man"]],
  ["Punk / Emo","1970s",["The Clash","Ramones","Sex Pistols","Blondie","Patti Smith","Buzzcocks","Siouxsie and the Banshees","The Damned","Television","X-Ray Spex","The Slits","Misfits"]],
  ["Punk / Emo","1980s",["Bad Religion","Dead Kennedys","Black Flag","The Replacements","Descendents","Minor Threat","Fugazi","Misfits","Hüsker Dü","Bad Brains","Circle Jerks","X"]],
  ["Punk / Emo","1990s",["Green Day","The Offspring","Blink-182","Rancid","NOFX","Jawbreaker","Jimmy Eat World","Fugazi","Bad Religion","Sunny Day Real Estate","Refused","Sleater-Kinney"]],
  ["Punk / Emo","2000s",["My Chemical Romance","Fall Out Boy","Paramore","Blink-182","Sum 41","AFI","Taking Back Sunday","Green Day","The Used","Dashboard Confessional","Brand New","Rise Against","Panic! at the Disco"]],
  ["Punk / Emo","2010s",["Paramore","The Wonder Years","Turnstile","PUP","The Story So Far","Joyce Manor","Title Fight","A Day to Remember","Modern Baseball","The Menzingers","La Dispute","Touché Amoré"]],
  ["Punk / Emo","2020s",["Turnstile","Paramore","Meet Me @ The Altar","The Linda Lindas","Militarie Gun","Scowl","Drug Church","Knocked Loose","Hot Mulligan","Mannequin Pussy","Gel","Home Is Where"]],
  ["Soul / Funk","1960s",["Aretha Franklin","James Brown","Otis Redding","Sam Cooke","The Supremes","Smokey Robinson","Nina Simone","Ray Charles","Wilson Pickett","Etta James","Ike & Tina Turner","Booker T. & the M.G.’s"]],
  ["Soul / Funk","1970s",["Stevie Wonder","Marvin Gaye","Earth, Wind & Fire","Parliament-Funkadelic","Chaka Khan","Curtis Mayfield","Sly and the Family Stone","Al Green","Bill Withers","The Isley Brothers","Kool & the Gang","Ohio Players"]],
  ["Soul / Funk","1980s",["Prince","Chaka Khan","Rick James","Sade","The Time","Luther Vandross","Anita Baker","George Clinton","Grace Jones","Teena Marie","Cameo","Patrice Rushen"]],
  ["Soul / Funk","1990s",["Lauryn Hill","Erykah Badu","D'Angelo","Maxwell","Jamiroquai","Mary J. Blige","Seal","Prince","Tony! Toni! Toné!","Meshell Ndegeocello","The Brand New Heavies","A Tribe Called Quest"]],
  ["Soul / Funk","2000s",["Amy Winehouse","Alicia Keys","Erykah Badu","D'Angelo","Jill Scott","John Legend","Joss Stone","Prince","OutKast","Musiq Soulchild","Raphael Saadiq","India.Arie"]],
];
