const DATA_PART_4 = [
  ["Jazz","2020s",["Kamasi Washington","Yussef Dayes","Laufey","Samara Joy","Nubya Garcia","BADBADNOTGOOD","Ezra Collective","Makaya McCraven","Shabaka","DOMi & JD Beck","Kokoroko","Meshell Ndegeocello"]],
  ["Reggae","1970s",["Bob Marley & The Wailers","Peter Tosh","Jimmy Cliff","Toots and the Maytals","Burning Spear","Gregory Isaacs","The Heptones","Black Uhuru","Dennis Brown","Lee “Scratch” Perry","Augustus Pablo","Culture"]],
  ["Reggae","1980s",["Bob Marley & The Wailers","Black Uhuru","Gregory Isaacs","UB40","Yellowman","Steel Pulse","Burning Spear","Third World","Jimmy Cliff","Eek-A-Mouse","Dennis Brown","Ziggy Marley"]],
  ["Reggae","1990s",["Shaggy","Buju Banton","Beenie Man","Bounty Killer","Ziggy Marley","Sizzla","Capleton","Beres Hammond","Maxi Priest","Luciano","Super Cat","Chaka Demus & Pliers"]],
  ["Reggae","2000s",["Sean Paul","Damian Marley","Shaggy","Toots and the Maytals","Gentleman","Matisyahu","Stephen Marley","Sizzla","Collie Buddz","Buju Banton","Beres Hammond","Capleton"]],
  ["Reggae","2010s",["Chronixx","Protoje","Koffee","Damian Marley","Popcaan","Kabaka Pyramid","Tarrus Riley","Alborosie","Shaggy","Jesse Royal","Busy Signal","Stephen Marley"]],
  ["Reggae","2020s",["Koffee","Protoje","Chronixx","Kabaka Pyramid","Lila Iké","Jesse Royal","Shenseea","Popcaan","Skip Marley","Spice","Mortimer","Samory I"]],
  ["Folk / Americana","1960s",["Bob Dylan","Joni Mitchell","Joan Baez","Simon & Garfunkel","Leonard Cohen","Neil Young","Judy Collins","Pete Seeger","Odetta","Gordon Lightfoot","The Byrds","Buffalo Springfield"]],
  ["Folk / Americana","1970s",["Joni Mitchell","Bob Dylan","Neil Young","Leonard Cohen","Carole King","James Taylor","Cat Stevens","Jackson Browne","Emmylou Harris","Crosby, Stills, Nash & Young","John Prine","Townes Van Zandt"]],
  ["Folk / Americana","1980s",["Tracy Chapman","Bruce Springsteen","Leonard Cohen","Suzanne Vega","Lucinda Williams","Townes Van Zandt","Emmylou Harris","John Prine","Nanci Griffith","The Pogues","Cowboy Junkies","Richard Thompson"]],
  ["Folk / Americana","1990s",["Tracy Chapman","Lucinda Williams","Elliott Smith","Gillian Welch","Jeff Buckley","Ani DiFranco","Uncle Tupelo","Wilco","Nick Cave & the Bad Seeds","Steve Earle","John Prine","Cowboy Junkies"]],
  ["Folk / Americana","2000s",["Bon Iver","Sufjan Stevens","Iron & Wine","Fleet Foxes","Bright Eyes","The Decemberists","Wilco","Gillian Welch","The Avett Brothers","Regina Spektor","Joanna Newsom","Ray LaMontagne"]],
  ["Folk / Americana","2010s",["Bon Iver","Phoebe Bridgers","Hozier","The Lumineers","Mumford & Sons","Fleet Foxes","Father John Misty","Big Thief","Jason Isbell","First Aid Kit","Brandi Carlile","The War on Drugs"]],
  ["Folk / Americana","2020s",["Zach Bryan","Phoebe Bridgers","Big Thief","Noah Kahan","Hozier","Waxahatchee","Adrianne Lenker","MJ Lenderman","Tyler Childers","Sierra Ferrell","Orville Peck","Wednesday"]],
  ["Afrobeats / Afrobeat","1970s",["Fela Kuti","Tony Allen","Manu Dibango","Osibisa","Hugh Masekela","Ebo Taylor","Orlando Julius","King Sunny Adé","Mulatu Astatke","William Onyeabor"]],
  ["Afrobeats / Afrobeat","1980s",["Fela Kuti","King Sunny Adé","Youssou N’Dour","Salif Keita","Manu Dibango","Hugh Masekela","Tony Allen","Angélique Kidjo","Papa Wemba","Thomas Mapfumo"]],
  ["Afrobeats / Afrobeat","1990s",["Fela Kuti","Femi Kuti","Angélique Kidjo","Youssou N’Dour","Salif Keita","Lagbaja","Tony Allen","Papa Wemba","Lucky Dube","Baaba Maal"]],
  ["Afrobeats / Afrobeat","2000s",["Femi Kuti","D’banj","2Baba","P-Square","Wizkid","Angélique Kidjo","Tony Allen","Seun Kuti","Wande Coal","M.I Abaga","Asa","9ice"]],
  ["Afrobeats / Afrobeat","2010s",["Burna Boy","Wizkid","Davido","Mr Eazi","Tiwa Savage","Yemi Alade","Tekno","Maleek Berry","Rema","Femi Kuti","Sarkodie","Stonebwoy"]],
  ["Afrobeats / Afrobeat","2020s",["Burna Boy","Wizkid","Tems","Rema","Davido","Tyla","Asake","Ayra Starr","Fireboy DML","Omah Lay","Amaarae","Uncle Waffles"]],
  ["K-Pop","1990s",["Seo Taiji and Boys","H.O.T.","S.E.S.","Fin.K.L","Shinhwa","g.o.d","Baby V.O.X","Sechs Kies","Uhm Jung-hwa","J.Y. Park"]],
  ["K-Pop","2000s",["BIGBANG","Girls’ Generation","TVXQ!","Super Junior","Wonder Girls","2NE1","SHINee","BoA","Rain","Epik High","KARA","Brown Eyed Girls"]],
  ["K-Pop","2010s",["BTS","BLACKPINK","EXO","TWICE","Red Velvet","SHINee","Girls’ Generation","BIGBANG","IU","SEVENTEEN","NCT 127","MAMAMOO"]],
  ["K-Pop","2020s",["BTS","BLACKPINK","NewJeans","Stray Kids","aespa","SEVENTEEN","LE SSERAFIM","IVE","(G)I-DLE","ENHYPEN","ATEEZ","TWICE","TXT","ITZY"]],
];
